#启用后需重启服务器
Mysql:
  enable: false
  url: 'localhost:3306'
  username: 'root'
  password: 'root'
  database: 'payworld'


#玩家时长耗尽传送回的世界
BackWorld: 'world'

#需要付费进入的世界
World:
#- 'world'

#世界别名
WorldAlias:
#- 'world:主世界'

Card:
  item: 'PAPER'
  name: '&6&l时长兑换卡'
  lore:
    - '&7- &a&l世界: %world%'
    - '&7- &b&l时长: %worldTime%'



Messages:
  addTime: '&a[PayWorld] &e您在 &b%world% &e的时长增加了 &b%worldTime% &e分钟'
  setTime: '&a[PayWorld] &e已将该玩家在 &b%world% &e的时长设置为 &b%worldTime% &e分钟'
  giveCrad: '&a[PayWorld] &e成功给予了该玩家在 &b%world% &e时长为 &b%worldTime% &e分钟的时长卡'
  listTitle: '&a[PayWorld] &e世界时长:'
  list: '&7- &b%world%:&e%worldTime%'
  lackTime: '&a[PayWorld] &e对不起您剩余的时长不足,无法传送进入该世界!'
  timeOut: '&a[PayWorld] &e您在此世界时长已经耗尽,您已被传送回默认世界!'
  notConsole: '&a[PayWorld] &c此命令不能再控制台中执行!'
  configNoWorld: '&a[PayWorld] &c这个世界不存在于配置文件中!'
  inputError: '&a[PayWorld] &c您的命令输入错误了\n&r- &a方法: &e/pw <Add/Set/Give> <PlayerName> <WorldName> <Time>'
  cardValueErr: '&a[PayWorld] &c读取卡片参数异常,请联系管理员进行处理!'
  offline: '&a[PayWorld] &c这个玩家不在线!'
  backpack: '&a[PayWorld] &c这个玩家的背包已满!'
  NoAPI: '&a[PayWorld] &c没有找到 PlaceholderAPI 已关闭此功能!'
  reload: '&a[PayWorld]&e 配置文件重载完成!'


