#玩家时长耗尽传送回的世界
BackWorld: 'world'

#需要付费进入的世界
World:
#- 'world'

Messages:
  lackTime: '&a[PayWorld] &e对不起您剩余的时长不足,无法传送进入该世界!'
  timeOut: '&a[PayWorld] &e您在此世界时长已经耗尽,您已被传送回默认世界!'
  notConsole: '&a[PayWorld] &c此命令不能再控制台中执行!'
  configNoWorld: '&a[PayWorld] &c这个世界不存在与配置文件中!'
  inputError: '&a[PayWorld] &c您的命令输入错误了\n&r- &a方法: &e/pw <Add/Set/Give> <PlayerName> <WorldName> <Time>'
  giveTime: '&a[PayWorld] &e您在 &b%world% &e的时长增加到了 &b%worldTime% &e分钟'
  offline: '&a[PayWorld] &c这个玩家不在线!'
  backpack: '&a[PayWorld] &c这个玩家的背包已满!'
  worldTimeList: '&a[PayWorld] &e世界时长:'
  reload: '&a[PayWorld]&e 配置文件重载完成!'


