name: PayWorld
version: ${project.version}
main: xyz.lvsheng.payworld.PayWorld
commands:
  payworld:
    aliases:
      - pw
permissions:
  payworld.show:
    default: not op
  payworld.admin:
    default: op
